// Manthana — domain types

export type Tier = "A" | "B" | "C" | "H";
export type Catalog = "nvidia_backed" | "research_assisted" | "hybrid_nvidia_quaasx108";

/** Web citation surfaced on a report (Hybrid live-capture flow). */
export interface WebCitation {
  title: string;
  url: string;
  source?: string;   // e.g. "PubMed", "AAFP", "NIH"
  snippet?: string;
}

/** Follow-up Q generated by Kimi after first analysis pass. */
export interface FollowUpQuestion {
  id: string;
  question: string;
  kind: "yesno" | "text" | "choice";
  options?: string[];
}
export type MedicalSystem =
  | "allopathy"
  | "ayurveda"
  | "homeopathy"
  | "siddha"
  | "unani"
  | "dental";
export type VerificationStatus = "pending" | "verified" | "rejected" | "manual_review";
export type ModalityCategory =
  | "X-Ray"
  | "CT"
  | "MRI"
  | "Ultrasound"
  | "ECG"
  | "Pathology"
  | "Photo"
  | "Video"
  | "Nuclear";

export interface Modality {
  slug: string;
  label: string;
  category: ModalityCategory;
  tier: Tier;
  catalog: Catalog;
  /** Shorthand for what the modality captures. */
  blurb?: string;
}

export type StudyStatus =
  | "draft"
  | "uploading"
  | "questionnaire"
  | "analyzing"
  | "awaiting_review"
  | "delivered"
  | "error";

export type Severity = "low" | "medium" | "high" | "critical";
export type Urgency = "routine" | "urgent" | "stat";

export interface Differential {
  dx: string;                       // diagnosis name
  likelihood: number;               // 0-1
  supportingFeatures?: string[];
  opposingFeatures?: string[];
  icd10Code?: string;
}

export interface Finding {
  id: string;
  title: string;
  description: string;
  severity: Severity;
  confidence: number;               // 0-1
  region?: string;
  // ── Clinically structured (optional, backwards-compatible) ──
  anatomicalRegion?: string;        // e.g. "Right upper lobe"
  observation?: string;             // factual observation (anatomy + abnormality)
  impression?: string;              // 1-line clinical impression
  recommendation?: string;          // next step / follow-up
  icd10Code?: string;               // e.g. "J18.1"
  icd10Label?: string;              // e.g. "Lobar pneumonia, unspecified organism"
  snomedCode?: string;              // e.g. "385093006"
  snomedLabel?: string;
  urgency?: Urgency;
  differentials?: Differential[];   // ranked
  // ── Urgency escalation gate (urgent / stat) ──
  escalationAcknowledged?: boolean;
  escalationCallbackTarget?: string;
  escalationCommunicationNote?: string;
  escalationAcknowledgedAt?: string;
  escalationAcknowledgedBy?: string;
}

export interface Report {
  studyId: string;
  narrative: string;
  findings: Finding[];
  overallConfidence: number;
  informationGaps?: string[];       // Tier C only
  foundationModelCaveat?: string;   // Tier C only
  // ── Critical-finding workflow (ACR actionable findings) ──
  criticalAcknowledgedAt?: string;  // ISO timestamp
  criticalAcknowledgedBy?: string;  // doctor full name
  criticalCallbackTarget?: string;  // who was called (referrer / patient / OPD)
  // ── Patient-facing plain-language summary (template) ──
  patientSummary?: string;
  // ── Authoritative web references (PubMed, NIH, AAFP, etc.) ──
  webCitations?: WebCitation[];
}

export type AssetKind = "image" | "video";
export interface PreviewAsset {
  kind: AssetKind;
  src: string;          // object URL or remote
  name?: string;
  durationSec?: number; // video only
}

export interface Study {
  id: string;
  modality: Modality;
  createdAt: string;
  status: StudyStatus;
  imagesCount: number;
  videosCount: number;
  reviewConfirmedAt?: string;
  reviewingDoctorNote?: string;
  report?: Report;
  patientRefShort?: string; // never PHI — initials/short ref only
  /** Local preview assets (object URLs) for in-app viewer. Not uploaded to server in this prototype. */
  previewAssets?: PreviewAsset[];
  /** True once a doctor has edited the AI report. AI version preserved server-side. */
  editedByDoctor?: boolean;
  /** True after the report is signed (locked). No further edits allowed. */
  reportLocked?: boolean;
}

export interface QuestionOption {
  value: string;
  label: string;
}
export type QuestionKind = "yesno" | "multi" | "number" | "text";

export interface Question {
  id: string;
  prompt: string;
  helper?: string;
  kind: QuestionKind;
  options?: QuestionOption[];
  required?: boolean;
  min?: number;
  max?: number;
  unit?: string;
}

export interface DoctorProfile {
  fullName: string;
  email: string;
  councilNumber: string;
  specialty?: string;
  attestedAt?: string;
  system?: MedicalSystem;
  councilBody?: string;
  councilState?: string;
  councilYear?: number;
  verificationStatus?: VerificationStatus;
}
